- name: Upgrade system
  include_role:
    name: upgrade_packages

- name: Install packages
  include_role:
    name: install_packages

- name: Configure etckeeper
  include_role:
    name: etckeeper
