new_servers:
  hosts:
    test_oracle_1:
      ansible_host: 129.151.87.105
      ansible_port: 22
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    test_oracle_2:
      ansible_host: 129.151.77.107
      ansible_port: 22
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    test_hetzner_1:
      ansible_host: 157.180.90.27
      ansible_port: 22
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

cloud:
  hosts:
    cloud7:
      ansible_host: cloud7.muflone.com
      ansible_port: 31241
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_become: true
    cloud8:
      ansible_host: cloud8.muflone.com
      ansible_port: 30122
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    cloud9:
      ansible_host: cloud9.muflone.com
      ansible_port: 31242
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_become: true
    test2:
      ansible_host: test2.muflone.com
      ansible_port: 31243
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

disabled:
  hosts:
