new_servers:
  hosts:
    new_server_1:
      ansible_host: 157.180.90.27
      ansible_user: root
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_python_interpreter: /usr/bin/python3

cloud:
  hosts:
    cloud7:
      ansible_host: cloud7.muflone.com
      ansible_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3
      ansible_become: true
    test2:
      ansible_host: 157.180.90.27
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
