new_servers:
  hosts:
    new_server_1:
      ansible_host: test2.muflone.com
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    new_server_2:
      ansible_host: cloud8.muflone.com
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

cloud:
  hosts:
    cloud7.muflone.com:
      ansible_host: cloud7.muflone.com
      ansible_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3
      ansible_become: true
    cloud8.muflone.com:
      ansible_host: cloud8.muflone.com
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    test2.muflone.com:
      ansible_host: test2.muflone.com
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
