new_servers:
  hosts:
    new_oracle_2:
      ansible_host: 129.151.77.107
      ansible_port: 22
      ansible_user: root
    new_hetzner_1:
      ansible_host: 135.181.107.14
      ansible_port: 22
      ansible_user: root
    new_hetzner_2:
      ansible_host: 157.180.90.27
      ansible_port: 22
      ansible_user: root

cloud:
  hosts:
    cloud7:
      ansible_host: cloud7.muflone.com
      ansible_port: 31241
      ansible_user: root
    cloud8:
      ansible_host: cloud8.muflone.com
      ansible_port: 30122
      ansible_user: root
    cloud9:
      ansible_host: cloud9.muflone.com
      ansible_port: 31242
      ansible_user: root
    test1:
      ansible_host: test1.muflone.com
      ansible_port: 31244
      ansible_user: root
    test2:
      ansible_host: test2.muflone.com
      ansible_port: 31243
      ansible_user: root

disabled:
  hosts:
    test1
