- name: Install package git-crypt
  ansible.builtin.include_role:
    name: install_packages
  vars:
    install_packages_packages:
      - git-crypt

- name: Check if a git-crypt sentinel file is encrypted
  when:
    - git_repo_git_repository is defined
    - git_repo_repository_dir is defined
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      head -c 10 "{{ git_repo_repository_dir }}/{{ git_repo_git_crypt_sentinel }}" | grep -q "GITCRYPT"
  register: git_repo_git_crypt_encrypted
  failed_when: false
  changed_when: false

- name: Export git-crypt key
  when:
    - git_repo_git_repository is defined
    - git_repo_repository_dir is defined
    - git_repo_git_crypt_encrypted.rc == 0
  ansible.builtin.copy:
    dest: "{{ git_repo_repository_dir }}/git-crypt.key"
    content: '{{ git_repo_git_crypt | b64decode }}'
    mode: "u=rw,g=,o="

- name: Decrypt files with git-crypt key
  when:
    - git_repo_git_repository is defined
    - git_repo_repository_dir is defined
    - git_repo_git_crypt_encrypted.rc == 0
  ansible.builtin.command:
    argv:
      - git-crypt
      - unlock
      - "{{ git_repo_repository_dir }}/git-crypt.key"
    chdir: "{{ git_repo_repository_dir }}"
  changed_when:
    - git_repo_git_crypt_encrypted.rc == 0

- name: Shred the git-crypt key
  when:
    - git_repo_git_repository is defined
    - git_repo_repository_dir is defined
    - git_repo_git_crypt_encrypted.rc == 0
  ansible.builtin.command:
    argv:
      - shred
      - "{{ git_repo_repository_dir }}/git-crypt.key"
  changed_when:
    - git_repo_git_crypt_encrypted.rc == 0

- name: Remove the git-crypt key
  when:
    - git_repo_git_repository is defined
    - git_repo_repository_dir is defined
    - git_repo_git_crypt_encrypted.rc == 0
  ansible.builtin.file:
    path: "{{ git_repo_repository_dir }}/git-crypt.key"
    state: absent
