- name: Configure network (static)
  when:
    - not dhcp | default(false)
  block:
    - name: Install 10-static-ethernet.network
      template:
        src: 10-static-ethernet.network.j2
        dest: "{{ chroot_path }}/etc/systemd/network/10-static-ethernet.network"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart networkd

    - name: Create drop-in directory for 10-static-ethernet.network
      file:
        path: "{{ chroot_path }}/etc/systemd/network/10-static-ethernet.network.d"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Configure static dns (static)
      copy:
        src: dns.conf
        dest: "{{ chroot_path }}/etc/systemd/network/10-static-ethernet.network.d/dns.conf"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart networkd
      when:
        - static_dns | default(true)

- name: Configure network (dhcp)
  when:
    - dhcp | default(false)
  block:
    - name: Install 10-dhcp-ethernet.network
      template:
        src: 10-dhcp-ethernet.network.j2
        dest: "{{ chroot_path }}/etc/systemd/network/10-dhcp-ethernet.network"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart networkd

    - name: Create drop-in directory for 10-dhcp-ethernet.network
      file:
        path: "{{ chroot_path }}/etc/systemd/network/10-dhcp-ethernet.network.d"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Configure static dns (dhcp)
      copy:
        src: dns.conf
        dest: "{{ chroot_path }}/etc/systemd/network/10-dhcp-ethernet.network.d/dns.conf"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart networkd
      when:
        - static_dns | default(false)

- name: Configure additional network addresses
  template:
    src: additional_addresses.conf.j2
    dest: >
      {{ chroot_path }}/etc/systemd/network/
      10-{{ 'dhcp' if dhcp | default(false) else 'static' }}-ethernet.network.d/
      additional_addresses.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart networkd
  when:
    - additional_addresses is defined

- name: Create symlink to resolv.conf
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: "{{ chroot_path }}/etc/resolv.conf"
    state: link
    force: true
    follow: false
    owner: root
    group: root

- name: Enable systemd-network services inside chroot
  command:
    argv:
      - chroot
      - "{{ chroot_path }}"
      - systemctl
      - enable
      - systemd-networkd
      - systemd-resolved
