- name: Configure SSH settings via drop-in
  ansible.builtin.copy:
    src: 90-sshd.conf
    dest: "{{ install_arch_chroot_path }}/etc/ssh/sshd_config.d/90-sshd.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Configure SSH port via drop-in
  when:
    - sshd_port is defined
  ansible.builtin.template:
    src: 91-sshd-port.conf.j2
    dest: "{{ install_arch_chroot_path }}/etc/ssh/sshd_config.d/91-sshd-port.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Copy SSH authorized_keys to /root/.ssh
  ansible.builtin.copy:
    src: authorized_keys
    dest: "{{ install_arch_chroot_path }}/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: "u=rw,g=,o="

- name: Enable service sshd inside chroot
  ansible.builtin.command:
    argv:
      - chroot
      - "{{ install_arch_chroot_path }}"
      - systemctl
      - enable
      - sshd
  register: install_arch_chroot_ssh_enable
  changed_when:
    - "install_arch_chroot_ssh_enable.rc == 0"
