- name: Install GRUB (MBR)
  ansible.builtin.command:
    argv:
      - chroot
      - "{{ install_arch_chroot_path }}"
      - grub-install
      - --target=i386-pc
      - --recheck
      - "{{ item }}"
  with_items:
    - "{{ system_disks }}"
  register: install_arch_chroot_grub_install_legacy
  changed_when:
    - "install_arch_chroot_grub_install_legacy.rc == 0"

- name: Install GRUB (EFI)
  when:
    - ansible_virtualization_role == 'host'
  ansible.builtin.command:
    argv:
      - chroot
      - "{{ install_arch_chroot_path }}"
      - grub-install
      - --target=x86_64-efi
      - --efi-directory=/efi
      - --removable
      - --recheck
      - "{{ item }}"
  with_items:
    - "{{ system_disks }}"
  register: install_arch_chroot_grub_install_uefi
  changed_when:
    - "install_arch_chroot_grub_install_uefi.rc == 0"

- name: Configure GRUB
  ansible.builtin.command:
    argv:
      - chroot
      - "{{ install_arch_chroot_path }}"
      - grub-mkconfig
      - --output=/boot/grub/grub.cfg
  register: install_arch_chroot_grub_mkconfig
  changed_when:
    - "install_arch_chroot_grub_mkconfig.rc == 0"
