- name: Configure sshd settings via drop-in
  ansible.builtin.copy:
    src: 90-sshd.conf
    dest: "{{ chroot_path }}/etc/ssh/sshd_config.d/90-sshd.conf"
    owner: root
    group: root
    mode: "0644"

- name: Copy SSH authorized_keys to /root/.ssh
  ansible.builtin.copy:
    src: authorized_keys
    dest: "{{ chroot_path }}/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: "0600"

- name: Enable service sshd inside chroot
  ansible.builtin.command:
    argv:
      - chroot
      - "{{ chroot_path }}"
      - systemctl
      - enable
      - sshd
