- name: Unmount filesystems from the chroot
  when:
    - false
  ansible.posix.mount:
    path: "{{ item }}"
    state: unmounted
  with_items:
    - "{{ install_arch_chroot_path }}/proc/sys/fs/binfmt_misc"
    - "{{ install_arch_chroot_path }}/dev/shm"
    - "{{ install_arch_chroot_path }}/dev/hugepages"
    - "{{ install_arch_chroot_path }}/dev/mqueue"

- name: Unmount others filesystems from the chroot
  ansible.builtin.command:
    argv:
      - umount
      - --lazy
      - "{{ item }}"
  with_items:
    - "{{ install_arch_chroot_path }}/dev"
    - "{{ install_arch_chroot_path }}/proc"
    - "{{ install_arch_chroot_path }}/sys"
  changed_when:
    - true

- name: Unmount /efi from the chroot
  when:
    - ansible_virtualization_role == 'host'
  ansible.posix.mount:
    path: "{{ install_arch_chroot_path }}/efi"
    state: unmounted

- name: Unmount chroot from the chroot
  ansible.builtin.command:
    argv:
      - umount
      - --lazy
      - "{{ install_arch_chroot_path }}"
  changed_when:
    - true
