- name: Configure network (static)
  when:
    - not dhcp | default(false)
  block:
    - name: Install 10-static-ethernet.network
      ansible.builtin.template:
        src: 10-static-ethernet.network.j2
        dest: "{{ install_arch_chroot_path }}/etc/systemd/network/10-static-ethernet.network"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart networkd

    - name: Create drop-in directory for 10-static-ethernet.network
      ansible.builtin.file:
        path: "{{ install_arch_chroot_path }}/etc/systemd/network/10-static-ethernet.network.d"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Configure static dns (static)
      when:
        - static_dns | default(true)
      ansible.builtin.copy:
        src: dns.conf
        dest: "{{ install_arch_chroot_path }}/etc/systemd/network/10-static-ethernet.network.d/dns.conf"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart networkd

- name: Configure network (dhcp)
  when:
    - dhcp | default(false)
  block:
    - name: Install 10-dhcp-ethernet.network
      ansible.builtin.template:
        src: 10-dhcp-ethernet.network.j2
        dest: "{{ install_arch_chroot_path }}/etc/systemd/network/10-dhcp-ethernet.network"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart networkd

    - name: Create drop-in directory for 10-dhcp-ethernet.network
      ansible.builtin.file:
        path: "{{ install_arch_chroot_path }}/etc/systemd/network/10-dhcp-ethernet.network.d"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Configure static dns (dhcp)
      when:
        - static_dns | default(false)
      ansible.builtin.copy:
        src: dns.conf
        dest: "{{ install_arch_chroot_path }}/etc/systemd/network/10-dhcp-ethernet.network.d/dns.conf"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart networkd

- name: Configure additional network addresses
  when:
    - additional_addresses is defined
  ansible.builtin.template:
    src: additional_addresses.conf.j2
    dest: >
      {{ install_arch_chroot_path }}/etc/systemd/network/
      10-{{ 'dhcp' if dhcp | default(false) else 'static' }}-ethernet.network.d/
      additional_addresses.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart networkd

- name: Create symlink to resolv.conf
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: "{{ install_arch_chroot_path }}/etc/resolv.conf"
    state: link
    force: true
    follow: false
    owner: root
    group: root

- name: Enable systemd-network services inside chroot
  ansible.builtin.command:
    argv:
      - chroot
      - "{{ install_arch_chroot_path }}"
      - systemctl
      - enable
      - systemd-networkd
      - systemd-resolved
  register: install_arch_chroot_networking_enable
  changed_when:
    - "install_arch_chroot_networking_enable.rc == 0"
