- name: Set chroot path
  ansible.builtin.set_fact:
    install_arch_chroot_path: "/mnt"

- name: Mount the root filesystem
  when:
    - filesystem == "ext4"
  ansible.posix.mount:
    src: "{{ system_disks[0] }}{{ 'p' if 'nvme' in system_disks[0] }}{{ install_arch_root_partno }}"
    path: "{{ install_arch_chroot_path }}"
    state: mounted
    fstype: ext4

- name: Create the efi mountpoint
  when:
    - partition_type == 'efi'
  ansible.builtin.file:
    path: "{{ install_arch_chroot_path }}/efi"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Mount the efi filesystem
  when:
    - partition_type == 'efi'
  ansible.posix.mount:
    src: "{{ system_disks[0] }}{{ 'p2' if 'nvme' in system_disks[0] else '2' }}"
    path: "{{ install_arch_chroot_path }}/efi"
    state: mounted
    fstype: vfat

- name: Mount chroot to bootstrap chroot
  when:
    - filesystem == "ext4"
  ansible.posix.mount:
    src: "{{ install_arch_chroot_path }}"
    path: /tmp/root.x86_64/mnt
    state: mounted
    fstype: ext4
    opts: rbind

- name: Mount /proc to new chroot
  ansible.posix.mount:
    src: /proc
    path: "{{ install_arch_chroot_path }}/proc"
    state: mounted
    fstype: proc
    opts: rbind

- name: Mount /sys to new chroot
  ansible.posix.mount:
    src: /sys
    path: "{{ install_arch_chroot_path }}/sys"
    state: mounted
    fstype: sysfs
    opts: rbind

- name: Mount /dev to new chroot
  ansible.posix.mount:
    src: /dev
    path: "{{ install_arch_chroot_path }}/dev"
    state: mounted
    fstype: udev
    opts: rbind
