- name: Check requirements
  ansible.builtin.include_tasks: requirements.yml

- name: Prepare Alpine environment
  when:
    - install_arch_rescue_type == 'oracle-alpine'
  ansible.builtin.include_tasks: prepare_oracle_alpine.yml

- name: Partitioning
  ansible.builtin.include_tasks: partitioning.yml

- name: Get Arch Linux bootstrap ISO
  ansible.builtin.include_tasks: bootstrap.yml

- name: Mount devices in the chroot
  ansible.builtin.include_tasks: chroot_mount.yml

- name: Configure pacman mirror
  ansible.builtin.template:
    src: mirrorlist.j2
    dest: /tmp/root.x86_64/etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Initialize pacman keyring inside bootstrap chroot
  ansible.builtin.command:
    argv:
      - chroot
      - /tmp/root.x86_64
      - pacman-key
      - --init
  register: install_arch_chroot_pacman_key_init
  changed_when:
    - "install_arch_chroot_pacman_key_init.rc == 0"

- name: Populate pacman keyring inside bootstrap chroot
  ansible.builtin.command:
    argv:
      - chroot
      - /tmp/root.x86_64
      - pacman-key
      - --populate
      - archlinux
  register: install_arch_chroot_pacman_key_populate
  changed_when:
    - "install_arch_chroot_pacman_key_populate.rc == 0"

- name: Install Arch Linux base from bootstrap chroot
  ansible.builtin.command:
    argv:
      - chroot
      - /tmp/root.x86_64
      - pacstrap
      - "{{ install_arch_chroot_path }}"
      - base
      - linux
      - grub
      - openssh
      - pacman-contrib
      - nano
      - python3
    creates: /tmp/root.x86_64/mnt/bin

- name: Install Arch Linux extra packages from bootstrap chroot
  when:
    - partition_type == 'efi'
  ansible.builtin.command:
    argv:
      - chroot
      - /tmp/root.x86_64
      - pacstrap
      - "{{ install_arch_chroot_path }}"
      - efibootmgr
    creates: /tmp/root.x86_64/mnt/bin

- name: Install ucode update
  when:
    - ansible_virtualization_role == 'host'
  ansible.builtin.include_tasks: ucode.yaml

- name: Run systemd-firstboot
  ansible.builtin.command:
    argv:
      - chroot
      - "{{ install_arch_chroot_path }}"
      - systemd-firstboot
      - --locale=C.UTF-8
      - --timezone=UTC
      - --hostname={{ hostname }}
  register: install_arch_chroot_systemd_firstboot
  changed_when:
    - "install_arch_chroot_systemd_firstboot.rc == 0"

- name: Run mkinitcpio
  ansible.builtin.command:
    argv:
      - chroot
      - "{{ install_arch_chroot_path }}"
      - mkinitcpio
      - --allpresets
  register: install_arch_chroot_mkinitcpio
  changed_when:
    - "install_arch_chroot_mkinitcpio.rc == 0"

- name: Setup pacman-init.service on first boot
  ansible.builtin.copy:
    src: pacman-init.service
    dest: "{{ install_arch_chroot_path }}/etc/systemd/system/"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Remove generated keyring in the installation process
  ansible.builtin.file:
    path: "{{ install_arch_chroot_path }}/etc/pacman.d/gnupg"
    state: absent

- name: Make sure /etc/machine-id is absent
  ansible.builtin.file:
    path: "{{ install_arch_chroot_path }}/etc/machine-id"
    state: absent

- name: Enable services inside chroot
  ansible.builtin.command:
    argv:
      - chroot
      - "{{ install_arch_chroot_path }}"
      - systemctl
      - enable
      - pacman-init
  register: install_arch_chroot_systemd_services
  changed_when:
    - "install_arch_chroot_systemd_services.rc == 0"

- name: Configure networking
  ansible.builtin.include_tasks: chroot_networking.yml

- name: Configure SSH
  ansible.builtin.include_tasks: chroot_ssh.yml

- name: Clean pacman cache
  ansible.builtin.command:
    argv:
      - chroot
      - "{{ install_arch_chroot_path }}"
      - paccache
      - --remove
      - --keep
      - 0
  register: install_arch_chroot_pacman_clean_cache
  changed_when:
    - "install_arch_chroot_pacman_clean_cache.rc == 0"

- name: Setup GRUB
  ansible.builtin.include_tasks: chroot_grub.yml

- name: Unmount devices from the chroot
  ansible.builtin.include_tasks: chroot_umount.yml

- name: Reboot
  ansible.builtin.reboot:
