- name: Install needed packages
  include_role:
    name: install_packages
  vars:
    packages:
      - etckeeper
      - less

- name: Set etckeeper source paths
  ansible.builtin.set_fact:
    etckeeper_src: "/etc/.git"

- name: Initialize etckeeper for /etc
  ansible.builtin.command:
    argv:
      - etckeeper
      - init
  args:
    creates: "{{ etckeeper_src }}"

- name: Check if /etc/.git exists
  ansible.builtin.stat:
    path: "{{ etckeeper_src }}"
  register: etckeeper_src_dir

- name: Check if /opt/etckeeper-etc.git exists
  ansible.builtin.stat:
    path: "{{ etckeeper_path }}"
  register: etckeeper_path_dir

- name: Copy etckeeper from /etc to /opt
  when:
    - etckeeper_src_dir.stat.isdir
  ansible.builtin.copy:
    src: "{{ etckeeper_src }}/"
    dest: "{{ etckeeper_path }}/"
    remote_src: yes
    mode: preserve
  register: etckeeper_src_copied

- name: Remove etckeeper from /etc
  when:
    - etckeeper_src_copied is succeeded
    - not etckeeper_src_dir.stat.islnk
  ansible.builtin.file:
    path: "{{ etckeeper_src }}"
    state: absent

- name: Create a symlink from /etc/.git to /opt/etckeeper-etc.git
  when:
    - etckeeper_src_copied is succeeded
    - not etckeeper_src_dir.stat.islnk
  ansible.builtin.file:
    src: "{{ etckeeper_path }}"
    dest: "{{ etckeeper_src }}"
    state: link

- name: Set committer user
  community.general.git_config:
    name: user.name
    value: "Muflone"
    repo: "{{ etckeeper_src }}"
    scope: global

- name: Set committer email
  community.general.git_config:
    name: user.email
    value: "muflone@localhost"
    repo: "{{ etckeeper_src }}"
    scope: global

- name: Update etckeeper for /etc
  ansible.builtin.command:
    argv:
      - etckeeper
      - commit
      - -m
      - "automatically commit changes in /etc"
  register: etckeeper_cmd
  changed_when:
    - etckeeper_cmd.rc == 0
  failed_when:
    - false

- name: Enable systemd timer
  ansible.builtin.service:
    name: etckeeper.timer
    enabled: yes
    state: started
