filesystem: "ext4"
system_disks:
  - /dev/sda
partition_type: 'mbr'
dhcp: false
hostname: "test2.muflone.com"
ipv4_address: 157.180.90.27
ipv4_netmask: /32
ipv4_gateway: 172.31.1.1
dns_servers:
  - 8.8.8.8
  - 8.8.4.4
sshd_port: 31241
