install_arch_system_disk: "/dev/sda"
install_arch_grub_needs_serial: true
install_arch_system_type: "efi"

hostname: "cloud9.muflone.com"
dhcp: true
dns_servers:
  - 8.8.8.8
  - 8.8.4.4
sshd_port: 31242
