- name: Maintenance
  hosts: cloud:!disabled
  gather_facts: true
  roles:
    - role: upgrade_packages

    - role: etckeeper

    - role: install_packages
      install_packages_packages: "{{ packages }}"

    - role: install_packages
      when:
        - packages_extra is defined
      install_packages_packages: "{{ packages_extra }}"
