- name: Maintenance for cloud8.muflone.com
  hosts: cloud8
  gather_facts: true
  roles:
    - role: upgrade_packages

    - role: etckeeper

    - role: install_packages
      install_packages_packages: "{{ packages }}"

    - role: docker

    - role: pulldocker
      pulldocker_path: "{{ base_path }}/cloud8-pulldocker"
