- name: Maintenance for cloud8.muflone.com
  hosts: cloud8
  gather_facts: true
  roles:
    - role: common

    - role: upgrade_packages

    - role: etckeeper

    - role: install_packages
      install_packages_packages: "{{ packages }}"

    - role: docker

    - role: git_repo
      git_repo_repository_dir: "{{ base_path }}/pulldocker"
      git_repo_git_repository: "https://github.com/muflone/docker-cloud-pulldocker"

    - role: pulldocker
      pulldocker_path: "{{ base_path }}/pulldocker"

    - role: git_repo
      git_repo_repository_dir: "{{ dockers_path }}/cloud8-mariadb"
      git_repo_git_repository: "https://github.com/muflone/docker-cloud-mariadb"

    - role: git_repo
      git_repo_repository_dir: "{{ dockers_path }}/cloud8-nextcloud"
      git_repo_git_repository: "https://github.com/muflone/docker-cloud-nextcloud"

    - role: git_repo
      git_repo_repository_dir: "{{ dockers_path }}/cloud8-nginx"
      git_repo_git_repository: "https://github.com/muflone/docker-cloud-nginx"

    - role: git_repo
      git_repo_repository_dir: "{{ dockers_path }}/cloud8-nginx/data/muflone.com"
      git_repo_git_repository: "https://github.com/muflone/muflone-rendered"

    - role: git_repo
      git_repo_repository_dir: "{{ dockers_path }}/cloud8-nginx/data/vbsimple.net"
      git_repo_git_repository: "https://github.com/muflone/vbsimple-rendered"

    - role: git_repo
      git_repo_repository_dir: "{{ dockers_path }}/cloud8-nginx-proxy-manager"
      git_repo_git_repository: "https://github.com/muflone/docker-cloud-nginx-proxy-manager"

    - role: git_repo
      git_repo_repository_dir: "{{ dockers_path }}/cloud8-pastey"
      git_repo_git_repository: "https://github.com/muflone/docker-cloud-pastey"

    - role: git_repo
      git_repo_repository_dir: "{{ dockers_path }}/cloud8-uptime-kuma"
      git_repo_git_repository: "https://github.com/muflone/docker-cloud-uptime-kuma"
      git_repo_git_crypt: "{{ cloud8_uptime_kuma_git_crypt }}"
      git_repo_git_crypt_sentinel: "app.env"

    - role: git_repo
      git_repo_repository_dir: "{{ dockers_path }}/cloud8-yourls"
      git_repo_git_repository: "https://github.com/muflone/docker-cloud-yourls"
      git_repo_git_crypt: "{{ cloud8_yourls_git_crypt }}"
      git_repo_git_crypt_sentinel: "app.env"

    - role: nextcloud
      nextcloud_mysql_user: "{{ cloud8_mysql_user }}"
      nextcloud_mysql_password: "{{ cloud8_mysql_password }}"
      nextcloud_path: "{{ dockers_path }}/cloud8-nextcloud"

    - role: git_repo
      git_repo_repository_dir: "{{ dockers_path }}/cloud8-borgmatic"
      git_repo_git_repository: "https://github.com/muflone/docker-cloud-borgmatic"
      git_repo_git_crypt: "{{ cloud8_borgmatic_git_crypt }}"
      git_repo_git_crypt_sentinel: "app.env"
